version: "3.5"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_USER=todo
    ports:
      - "5432:5432"
    networks:
      - livup
networks:
  livup:
    name: livup
