// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package schema

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TodoStatus int32

const (
	TodoStatus_UNKNOWN   TodoStatus = 0
	TodoStatus_ACTIVE    TodoStatus = 1
	TodoStatus_COMPLETED TodoStatus = 2
)

var TodoStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "ACTIVE",
	2: "COMPLETED",
}

var TodoStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"ACTIVE":    1,
	"COMPLETED": 2,
}

func (x TodoStatus) String() string {
	return proto.EnumName(TodoStatus_name, int32(x))
}

func (TodoStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

type NewTodoRequest struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTodoRequest) Reset()         { *m = NewTodoRequest{} }
func (m *NewTodoRequest) String() string { return proto.CompactTextString(m) }
func (*NewTodoRequest) ProtoMessage()    {}
func (*NewTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *NewTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTodoRequest.Unmarshal(m, b)
}
func (m *NewTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTodoRequest.Marshal(b, m, deterministic)
}
func (m *NewTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTodoRequest.Merge(m, src)
}
func (m *NewTodoRequest) XXX_Size() int {
	return xxx_messageInfo_NewTodoRequest.Size(m)
}
func (m *NewTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTodoRequest proto.InternalMessageInfo

func (m *NewTodoRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type NewTodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTodoResponse) Reset()         { *m = NewTodoResponse{} }
func (m *NewTodoResponse) String() string { return proto.CompactTextString(m) }
func (*NewTodoResponse) ProtoMessage()    {}
func (*NewTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *NewTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTodoResponse.Unmarshal(m, b)
}
func (m *NewTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTodoResponse.Marshal(b, m, deterministic)
}
func (m *NewTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTodoResponse.Merge(m, src)
}
func (m *NewTodoResponse) XXX_Size() int {
	return xxx_messageInfo_NewTodoResponse.Size(m)
}
func (m *NewTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTodoResponse proto.InternalMessageInfo

func (m *NewTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type GetTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoRequest) Reset()         { *m = GetTodoRequest{} }
func (m *GetTodoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTodoRequest) ProtoMessage()    {}
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *GetTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoRequest.Unmarshal(m, b)
}
func (m *GetTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoRequest.Marshal(b, m, deterministic)
}
func (m *GetTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoRequest.Merge(m, src)
}
func (m *GetTodoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTodoRequest.Size(m)
}
func (m *GetTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoRequest proto.InternalMessageInfo

func (m *GetTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoResponse) Reset()         { *m = GetTodoResponse{} }
func (m *GetTodoResponse) String() string { return proto.CompactTextString(m) }
func (*GetTodoResponse) ProtoMessage()    {}
func (*GetTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *GetTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoResponse.Unmarshal(m, b)
}
func (m *GetTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoResponse.Marshal(b, m, deterministic)
}
func (m *GetTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoResponse.Merge(m, src)
}
func (m *GetTodoResponse) XXX_Size() int {
	return xxx_messageInfo_GetTodoResponse.Size(m)
}
func (m *GetTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoResponse proto.InternalMessageInfo

func (m *GetTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type ListTodoRequest struct {
	Status               TodoStatus `protobuf:"varint,1,opt,name=status,proto3,enum=schema.TodoStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListTodoRequest) Reset()         { *m = ListTodoRequest{} }
func (m *ListTodoRequest) String() string { return proto.CompactTextString(m) }
func (*ListTodoRequest) ProtoMessage()    {}
func (*ListTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *ListTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoRequest.Unmarshal(m, b)
}
func (m *ListTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoRequest.Marshal(b, m, deterministic)
}
func (m *ListTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoRequest.Merge(m, src)
}
func (m *ListTodoRequest) XXX_Size() int {
	return xxx_messageInfo_ListTodoRequest.Size(m)
}
func (m *ListTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoRequest proto.InternalMessageInfo

func (m *ListTodoRequest) GetStatus() TodoStatus {
	if m != nil {
		return m.Status
	}
	return TodoStatus_UNKNOWN
}

type ListTodoResponse struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodoResponse) Reset()         { *m = ListTodoResponse{} }
func (m *ListTodoResponse) String() string { return proto.CompactTextString(m) }
func (*ListTodoResponse) ProtoMessage()    {}
func (*ListTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}

func (m *ListTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoResponse.Unmarshal(m, b)
}
func (m *ListTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoResponse.Marshal(b, m, deterministic)
}
func (m *ListTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoResponse.Merge(m, src)
}
func (m *ListTodoResponse) XXX_Size() int {
	return xxx_messageInfo_ListTodoResponse.Size(m)
}
func (m *ListTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoResponse proto.InternalMessageInfo

func (m *ListTodoResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type SetTodoRequest struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTodoRequest) Reset()         { *m = SetTodoRequest{} }
func (m *SetTodoRequest) String() string { return proto.CompactTextString(m) }
func (*SetTodoRequest) ProtoMessage()    {}
func (*SetTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6}
}

func (m *SetTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTodoRequest.Unmarshal(m, b)
}
func (m *SetTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTodoRequest.Marshal(b, m, deterministic)
}
func (m *SetTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTodoRequest.Merge(m, src)
}
func (m *SetTodoRequest) XXX_Size() int {
	return xxx_messageInfo_SetTodoRequest.Size(m)
}
func (m *SetTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTodoRequest proto.InternalMessageInfo

func (m *SetTodoRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type SetTodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTodoResponse) Reset()         { *m = SetTodoResponse{} }
func (m *SetTodoResponse) String() string { return proto.CompactTextString(m) }
func (*SetTodoResponse) ProtoMessage()    {}
func (*SetTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{7}
}

func (m *SetTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTodoResponse.Unmarshal(m, b)
}
func (m *SetTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTodoResponse.Marshal(b, m, deterministic)
}
func (m *SetTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTodoResponse.Merge(m, src)
}
func (m *SetTodoResponse) XXX_Size() int {
	return xxx_messageInfo_SetTodoResponse.Size(m)
}
func (m *SetTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTodoResponse proto.InternalMessageInfo

func (m *SetTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type DelTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTodoRequest) Reset()         { *m = DelTodoRequest{} }
func (m *DelTodoRequest) String() string { return proto.CompactTextString(m) }
func (*DelTodoRequest) ProtoMessage()    {}
func (*DelTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8}
}

func (m *DelTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTodoRequest.Unmarshal(m, b)
}
func (m *DelTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTodoRequest.Marshal(b, m, deterministic)
}
func (m *DelTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTodoRequest.Merge(m, src)
}
func (m *DelTodoRequest) XXX_Size() int {
	return xxx_messageInfo_DelTodoRequest.Size(m)
}
func (m *DelTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelTodoRequest proto.InternalMessageInfo

func (m *DelTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DelTodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTodoResponse) Reset()         { *m = DelTodoResponse{} }
func (m *DelTodoResponse) String() string { return proto.CompactTextString(m) }
func (*DelTodoResponse) ProtoMessage()    {}
func (*DelTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9}
}

func (m *DelTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTodoResponse.Unmarshal(m, b)
}
func (m *DelTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTodoResponse.Marshal(b, m, deterministic)
}
func (m *DelTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTodoResponse.Merge(m, src)
}
func (m *DelTodoResponse) XXX_Size() int {
	return xxx_messageInfo_DelTodoResponse.Size(m)
}
func (m *DelTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelTodoResponse proto.InternalMessageInfo

func (m *DelTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type Todo struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status               TodoStatus `protobuf:"varint,3,opt,name=status,proto3,enum=schema.TodoStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{10}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetStatus() TodoStatus {
	if m != nil {
		return m.Status
	}
	return TodoStatus_UNKNOWN
}

func init() {
	proto.RegisterEnum("schema.TodoStatus", TodoStatus_name, TodoStatus_value)
	proto.RegisterType((*NewTodoRequest)(nil), "schema.NewTodoRequest")
	proto.RegisterType((*NewTodoResponse)(nil), "schema.NewTodoResponse")
	proto.RegisterType((*GetTodoRequest)(nil), "schema.GetTodoRequest")
	proto.RegisterType((*GetTodoResponse)(nil), "schema.GetTodoResponse")
	proto.RegisterType((*ListTodoRequest)(nil), "schema.ListTodoRequest")
	proto.RegisterType((*ListTodoResponse)(nil), "schema.ListTodoResponse")
	proto.RegisterType((*SetTodoRequest)(nil), "schema.SetTodoRequest")
	proto.RegisterType((*SetTodoResponse)(nil), "schema.SetTodoResponse")
	proto.RegisterType((*DelTodoRequest)(nil), "schema.DelTodoRequest")
	proto.RegisterType((*DelTodoResponse)(nil), "schema.DelTodoResponse")
	proto.RegisterType((*Todo)(nil), "schema.Todo")
}

func init() {
	proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a)
}

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x4f, 0xfa, 0x30,
	0x18, 0xc6, 0xc7, 0xe0, 0x3f, 0xe0, 0x1d, 0xff, 0xb1, 0xf4, 0xa0, 0x84, 0xd3, 0xd2, 0x93, 0xe1,
	0xc0, 0x61, 0x18, 0x4f, 0x1a, 0xa3, 0x40, 0x8c, 0x11, 0x87, 0x61, 0xa8, 0x89, 0x37, 0x64, 0x4d,
	0x5c, 0xa2, 0x14, 0x69, 0xd1, 0x6f, 0xe8, 0xe7, 0x32, 0x2d, 0x65, 0xdd, 0x86, 0x86, 0x79, 0x5c,
	0xdf, 0xf7, 0xf7, 0x3c, 0xe9, 0xb3, 0xa7, 0xd0, 0x60, 0xf3, 0x17, 0xf2, 0x36, 0xeb, 0x2e, 0x57,
	0x94, 0x53, 0x64, 0x6d, 0xbe, 0xb0, 0x0f, 0x4e, 0x40, 0x3e, 0xa7, 0x34, 0xa2, 0x13, 0xf2, 0xbe,
	0x26, 0x8c, 0x23, 0x0f, 0x2a, 0x9c, 0x46, 0xb4, 0x55, 0xf2, 0x4a, 0x47, 0xb6, 0xdf, 0xe8, 0x2a,
	0x4c, 0xae, 0xc8, 0x09, 0xee, 0x41, 0x33, 0x61, 0xd8, 0x92, 0x2e, 0x18, 0x29, 0x00, 0x79, 0xe0,
	0x5c, 0x11, 0x9e, 0x36, 0x72, 0xc0, 0x8c, 0x23, 0x49, 0xd4, 0x27, 0x66, 0x1c, 0x09, 0xd9, 0x64,
	0xa3, 0xb0, 0xec, 0x19, 0x34, 0x47, 0x31, 0xcb, 0xe8, 0x76, 0xc0, 0x62, 0x7c, 0xc6, 0xd7, 0x4c,
	0x62, 0x8e, 0x8f, 0xd2, 0x58, 0x28, 0x27, 0x13, 0xb5, 0x81, 0x4f, 0xc0, 0xd5, 0xb8, 0x32, 0xc5,
	0xf0, 0x4f, 0x48, 0x0b, 0xbc, 0xbc, 0xe3, 0xba, 0x19, 0x89, 0xd8, 0xc2, 0xec, 0x6d, 0x0a, 0xc5,
	0x16, 0xfe, 0xf9, 0x7e, 0x1e, 0x38, 0x03, 0xf2, 0xba, 0x27, 0xb6, 0x64, 0xa3, 0xb0, 0x6c, 0x04,
	0x15, 0xf1, 0x95, 0x17, 0x43, 0x1e, 0xd8, 0x11, 0x61, 0xf3, 0x55, 0xbc, 0xe4, 0x31, 0x5d, 0xb4,
	0x4c, 0x39, 0x48, 0x1f, 0xa5, 0xd2, 0x2d, 0xef, 0x4b, 0xb7, 0x73, 0x0c, 0xa0, 0x4f, 0x91, 0x0d,
	0xd5, 0xfb, 0xe0, 0x26, 0x18, 0x3f, 0x06, 0xae, 0x81, 0x00, 0xac, 0x8b, 0xfe, 0xf4, 0xfa, 0x61,
	0xe8, 0x96, 0xd0, 0x7f, 0xa8, 0xf7, 0xc7, 0xb7, 0x77, 0xa3, 0xe1, 0x74, 0x38, 0x70, 0x4d, 0xff,
	0xcb, 0x04, 0x5b, 0x62, 0x64, 0xf5, 0x11, 0xcf, 0x09, 0x3a, 0x85, 0xaa, 0xaa, 0x1b, 0x3a, 0xd8,
	0x9a, 0x65, 0x3b, 0xdb, 0x3e, 0xdc, 0x39, 0xdf, 0x24, 0x81, 0x0d, 0x41, 0xab, 0x56, 0x69, 0x3a,
	0x5b, 0x44, 0x4d, 0xe7, 0xea, 0x87, 0x0d, 0x74, 0x0e, 0xb5, 0x6d, 0x3f, 0x50, 0xb2, 0x96, 0x2b,
	0x5c, 0xbb, 0xb5, 0x3b, 0x48, 0xdb, 0x87, 0x79, 0xfb, 0xf0, 0x17, 0xfb, 0x90, 0xfc, 0x40, 0xab,
	0x7f, 0xab, 0xe9, 0x6c, 0x1d, 0x34, 0x9d, 0x2b, 0x01, 0x36, 0x2e, 0x6b, 0x4f, 0xea, 0x95, 0x3f,
	0x5b, 0xf2, 0xd1, 0xf7, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xe6, 0xbb, 0x11, 0x04, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	NewTodo(ctx context.Context, in *NewTodoRequest, opts ...grpc.CallOption) (*NewTodoResponse, error)
	GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*GetTodoResponse, error)
	ListTodo(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error)
	SetTodo(ctx context.Context, in *SetTodoRequest, opts ...grpc.CallOption) (*SetTodoResponse, error)
	DelTodo(ctx context.Context, in *DelTodoRequest, opts ...grpc.CallOption) (*DelTodoResponse, error)
}

type todoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoServiceClient(cc grpc.ClientConnInterface) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) NewTodo(ctx context.Context, in *NewTodoRequest, opts ...grpc.CallOption) (*NewTodoResponse, error) {
	out := new(NewTodoResponse)
	err := c.cc.Invoke(ctx, "/schema.TodoService/NewTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*GetTodoResponse, error) {
	out := new(GetTodoResponse)
	err := c.cc.Invoke(ctx, "/schema.TodoService/GetTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ListTodo(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error) {
	out := new(ListTodoResponse)
	err := c.cc.Invoke(ctx, "/schema.TodoService/ListTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) SetTodo(ctx context.Context, in *SetTodoRequest, opts ...grpc.CallOption) (*SetTodoResponse, error) {
	out := new(SetTodoResponse)
	err := c.cc.Invoke(ctx, "/schema.TodoService/SetTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DelTodo(ctx context.Context, in *DelTodoRequest, opts ...grpc.CallOption) (*DelTodoResponse, error) {
	out := new(DelTodoResponse)
	err := c.cc.Invoke(ctx, "/schema.TodoService/DelTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	NewTodo(context.Context, *NewTodoRequest) (*NewTodoResponse, error)
	GetTodo(context.Context, *GetTodoRequest) (*GetTodoResponse, error)
	ListTodo(context.Context, *ListTodoRequest) (*ListTodoResponse, error)
	SetTodo(context.Context, *SetTodoRequest) (*SetTodoResponse, error)
	DelTodo(context.Context, *DelTodoRequest) (*DelTodoResponse, error)
}

// UnimplementedTodoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServiceServer struct {
}

func (*UnimplementedTodoServiceServer) NewTodo(ctx context.Context, req *NewTodoRequest) (*NewTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTodo not implemented")
}
func (*UnimplementedTodoServiceServer) GetTodo(ctx context.Context, req *GetTodoRequest) (*GetTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodo not implemented")
}
func (*UnimplementedTodoServiceServer) ListTodo(ctx context.Context, req *ListTodoRequest) (*ListTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTodo not implemented")
}
func (*UnimplementedTodoServiceServer) SetTodo(ctx context.Context, req *SetTodoRequest) (*SetTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTodo not implemented")
}
func (*UnimplementedTodoServiceServer) DelTodo(ctx context.Context, req *DelTodoRequest) (*DelTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelTodo not implemented")
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_NewTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).NewTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.TodoService/NewTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).NewTodo(ctx, req.(*NewTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.TodoService/GetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodo(ctx, req.(*GetTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ListTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ListTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.TodoService/ListTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ListTodo(ctx, req.(*ListTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_SetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).SetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.TodoService/SetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).SetTodo(ctx, req.(*SetTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DelTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DelTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schema.TodoService/DelTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DelTodo(ctx, req.(*DelTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schema.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTodo",
			Handler:    _TodoService_NewTodo_Handler,
		},
		{
			MethodName: "GetTodo",
			Handler:    _TodoService_GetTodo_Handler,
		},
		{
			MethodName: "ListTodo",
			Handler:    _TodoService_ListTodo_Handler,
		},
		{
			MethodName: "SetTodo",
			Handler:    _TodoService_SetTodo_Handler,
		},
		{
			MethodName: "DelTodo",
			Handler:    _TodoService_DelTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}
